name: docs

on:
  push:
    branches:
      - counter
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttsky25a
        with:
          tools-ref: ttsky25a
